import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PrescriptionPDFData {
  id: number;
  patientName: string;
  doctorName: string;
  diagnosis: string;
  medicines: { name: string; dosage?: string; duration?: string }[];
  labTests?: string[];
  notes?: string;
  createdAt: string;
  status: string;
}

export function generatePrescriptionPDF(data: PrescriptionPDFData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("Medicare HMS", pageWidth / 2, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text("Prescription Report", pageWidth / 2, 28, { align: "center" });
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 35, pageWidth - 20, 35);
  
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  
  let yPos = 45;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Prescription ID:", 20, yPos);
  doc.text("Date:", 120, yPos);
  
  doc.setTextColor(40, 40, 40);
  doc.text(`#${data.id}`, 50, yPos);
  doc.text(new Date(data.createdAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  }), 140, yPos);
  
  yPos += 10;
  
  doc.setTextColor(100, 100, 100);
  doc.text("Patient:", 20, yPos);
  doc.text("Doctor:", 120, yPos);
  
  doc.setTextColor(40, 40, 40);
  doc.text(data.patientName || "Patient", 50, yPos);
  doc.text(`Dr. ${data.doctorName || "Unknown"}`, 145, yPos);
  
  yPos += 10;
  
  doc.setTextColor(100, 100, 100);
  doc.text("Diagnosis:", 20, yPos);
  
  doc.setTextColor(40, 40, 40);
  const diagnosis = data.diagnosis || "Not specified";
  const diagnosisLines = doc.splitTextToSize(diagnosis, pageWidth - 50);
  doc.text(diagnosisLines, 50, yPos);
  yPos += diagnosisLines.length * 5 + 5;
  
  if (data.medicines && data.medicines.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text("Medicines", 20, yPos);
    yPos += 5;
    
    const medicineData = data.medicines.map((med, idx) => [
      idx + 1,
      med.name,
      med.dosage || "-",
      med.duration || "-"
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [["#", "Medicine Name", "Dosage", "Duration"]],
      body: medicineData,
      theme: "striped",
      headStyles: { fillColor: [76, 175, 80], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 20, right: 20 }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  if (data.labTests && data.labTests.length > 0) {
    if (yPos > 230) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text("Lab Tests", 20, yPos);
    yPos += 5;
    
    const labData = data.labTests.map((test, idx) => [idx + 1, test]);
    
    autoTable(doc, {
      startY: yPos,
      head: [["#", "Test Name"]],
      body: labData,
      theme: "striped",
      headStyles: { fillColor: [156, 39, 176], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 20, right: 20 }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  if (data.notes) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text("Notes", 20, yPos);
    yPos += 5;
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const notesLines = doc.splitTextToSize(data.notes, pageWidth - 40);
    doc.text(notesLines, 20, yPos);
  }
  
  const footerY = 280;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Medicare HMS", pageWidth / 2, footerY, { align: "center" });
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, footerY + 5, { align: "center" });
  
  doc.save(`prescription_${data.id}_${new Date().toISOString().split("T")[0]}.pdf`);
}
